version: "3.8"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: students

    expose:
      - "5000"
    ports:
      - "5000:5432"
  api:
    image: student-service
    depends_on:
      - db
    ports:
      - "4000:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/students
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password